// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2w9NposUHIeI-ZKXbzYm1U-cQRBoaDTw',
    appId: '1:100377539689:web:978528829f1ba600afdef8',
    messagingSenderId: '100377539689',
    projectId: 'fit-ai-analyzer',
    authDomain: 'fit-ai-analyzer.firebaseapp.com',
    storageBucket: 'fit-ai-analyzer.firebasestorage.app',
    measurementId: 'G-N8JVZ1ZPLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlSd1ze6AGnAIZ1_naHcjD4G3IURKzltw',
    appId: '1:100377539689:android:5d8aec00a5b231adafdef8',
    messagingSenderId: '100377539689',
    projectId: 'fit-ai-analyzer',
    storageBucket: 'fit-ai-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc5qvrY1RjtlPKV7Oxl2HkDxZjM3da1bI',
    appId: '1:100377539689:ios:603cf58890f916caafdef8',
    messagingSenderId: '100377539689',
    projectId: 'fit-ai-analyzer',
    storageBucket: 'fit-ai-analyzer.firebasestorage.app',
    iosBundleId: 'com.fitai.fitaiAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc5qvrY1RjtlPKV7Oxl2HkDxZjM3da1bI',
    appId: '1:100377539689:ios:603cf58890f916caafdef8',
    messagingSenderId: '100377539689',
    projectId: 'fit-ai-analyzer',
    storageBucket: 'fit-ai-analyzer.firebasestorage.app',
    iosBundleId: 'com.fitai.fitaiAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2w9NposUHIeI-ZKXbzYm1U-cQRBoaDTw',
    appId: '1:100377539689:web:3924278ca94fdb19afdef8',
    messagingSenderId: '100377539689',
    projectId: 'fit-ai-analyzer',
    authDomain: 'fit-ai-analyzer.firebaseapp.com',
    storageBucket: 'fit-ai-analyzer.firebasestorage.app',
    measurementId: 'G-ZN2E3S520F',
  );

}